---
sitecode: 13
sitename: Emerson Elementary School
siteabbreviation: EME
siteaddress: 2800 Forest Ave, Berkeley, CA 94705
sitegps: 37.8610751,-122.250278
is_trunk: false
vlans:
  Access : 10
  GuestWiFi : 20
  StudentWiFi : 30
  StaffWiFi : 40
  Management : 200