---
sitename: Rosa Parks Elementary School
sitecode: 24
siteabbreviation: RPE
siteaddress: 920 Allston Way, Berkeley, CA 94710
sitegps: 37.8654198,-122.297200
is_trunk: true
trunk_port: ethe 1/3/4
vlans:
  Access : 19
  GuestWiFi : 29
  StudentWiFi : 39
  StaffWiFi : 49
  Management : 299