---
- name: Router configs your District
  hosts: all


  tasks:
    - name: Create facts which are transformed from sitecode
      set_fact:
        ptp_uplink_prefix:    "{{ '10.9.0.0/21' | ansible.utils.ipsubnet(30, + hostvars[inventory_hostname].sitecode) }}"
        ptp_uplink_core_side: "{{ '10.9.0.0/21' | ansible.utils.ipsubnet(30, + hostvars[inventory_hostname].sitecode) | ansible.utils.ipmath(2) }}"
        ptp_uplink_site_side: "{{ '10.9.0.0/21' | ansible.utils.ipsubnet(30, + hostvars[inventory_hostname].sitecode) | ansible.utils.ipmath(3) }}"
    - name: Write a configuration for Ruckus Routers
      ansible.builtin.template:
        src: ruckus.j2
        dest: output/{{inventory_hostname}}_ruckus.txt
    - name: Write a configuration for Juniper Routers
      ansible.builtin.template:
        src: juniper.j2
        dest: output/{{inventory_hostname}}_juniper.txt